# TODO: Currently we only need USB HID for tablet input device, which is under CONFIG_USB
# If we can get rid of HID devices we can disable this and CONFIG_PCI_UHCI
CONFIG_USB=y

CONFIG_USB_TABLET_WACOM=n
CONFIG_USB_STORAGE_BOT=n
CONFIG_USB_STORAGE_UAS=n
CONFIG_USB_STORAGE_MTP=n
CONFIG_USB_SMARTCARD=n
CONFIG_USB_AUDIO=n
CONFIG_USB_SERIAL=n
CONFIG_USB_NETWORK=n
CONFIG_USB_BLUETOOTH=n
