/*
 * QEMU seccomp mode 2 support with libseccomp
 *
 * Copyright IBM, Corp. 2012
 *
 * Authors:
 *  Eduardo Otubo    <eotubo@br.ibm.com>
 *
 * This work is licensed under the terms of the GNU GPL, version 2.  See
 * the COPYING file in the top-level directory.
 *
 * Contributions after 2012-01-13 are licensed under the terms of the
 * GNU GPL, version 2 or (at your option) any later version.
 */
#ifndef QEMU_SECCOMP_H
#define QEMU_SECCOMP_H

#define QEMU_SECCOMP_SET_DEFAULT     (1 << 0)
#define QEMU_SECCOMP_SET_OBSOLETE    (1 << 1)
#define QEMU_SECCOMP_SET_PRIVILEGED  (1 << 2)
#define QEMU_SECCOMP_SET_SPAWN       (1 << 3)
#define QEMU_SECCOMP_SET_RESOURCECTL (1 << 4)

struct syscall_name_tbl {
    int nr;
    const char *name;
};

#define SYSCALL_NAME(NAME) { __NR_##NAME, #NAME }
#define SYSCALL_TABLE() { \
    SYSCALL_NAME(read), \
    SYSCALL_NAME(write), \
    SYSCALL_NAME(open), \
    SYSCALL_NAME(close), \
    SYSCALL_NAME(stat), \
    SYSCALL_NAME(fstat), \
    SYSCALL_NAME(lstat), \
    SYSCALL_NAME(poll), \
    SYSCALL_NAME(lseek), \
    SYSCALL_NAME(mmap), \
    SYSCALL_NAME(mprotect), \
    SYSCALL_NAME(munmap), \
    SYSCALL_NAME(brk), \
    SYSCALL_NAME(rt_sigaction), \
    SYSCALL_NAME(rt_sigprocmask), \
    SYSCALL_NAME(rt_sigreturn), \
    SYSCALL_NAME(ioctl), \
    SYSCALL_NAME(pread64), \
    SYSCALL_NAME(pwrite64), \
    SYSCALL_NAME(readv), \
    SYSCALL_NAME(writev), \
    SYSCALL_NAME(access), \
    SYSCALL_NAME(pipe), \
    SYSCALL_NAME(select), \
    SYSCALL_NAME(sched_yield), \
    SYSCALL_NAME(mremap), \
    SYSCALL_NAME(msync), \
    SYSCALL_NAME(mincore), \
    SYSCALL_NAME(madvise), \
    SYSCALL_NAME(shmget), \
    SYSCALL_NAME(shmat), \
    SYSCALL_NAME(shmctl), \
    SYSCALL_NAME(dup), \
    SYSCALL_NAME(dup2), \
    SYSCALL_NAME(pause), \
    SYSCALL_NAME(nanosleep), \
    SYSCALL_NAME(getitimer), \
    SYSCALL_NAME(alarm), \
    SYSCALL_NAME(setitimer), \
    SYSCALL_NAME(getpid), \
    SYSCALL_NAME(sendfile), \
    SYSCALL_NAME(socket), \
    SYSCALL_NAME(connect), \
    SYSCALL_NAME(accept), \
    SYSCALL_NAME(sendto), \
    SYSCALL_NAME(recvfrom), \
    SYSCALL_NAME(sendmsg), \
    SYSCALL_NAME(recvmsg), \
    SYSCALL_NAME(shutdown), \
    SYSCALL_NAME(bind), \
    SYSCALL_NAME(listen), \
    SYSCALL_NAME(getsockname), \
    SYSCALL_NAME(getpeername), \
    SYSCALL_NAME(socketpair), \
    SYSCALL_NAME(setsockopt), \
    SYSCALL_NAME(getsockopt), \
    SYSCALL_NAME(clone), \
    SYSCALL_NAME(fork), \
    SYSCALL_NAME(vfork), \
    SYSCALL_NAME(execve), \
    SYSCALL_NAME(exit), \
    SYSCALL_NAME(wait4), \
    SYSCALL_NAME(kill), \
    SYSCALL_NAME(uname), \
    SYSCALL_NAME(semget), \
    SYSCALL_NAME(semop), \
    SYSCALL_NAME(semctl), \
    SYSCALL_NAME(shmdt), \
    SYSCALL_NAME(msgget), \
    SYSCALL_NAME(msgsnd), \
    SYSCALL_NAME(msgrcv), \
    SYSCALL_NAME(msgctl), \
    SYSCALL_NAME(fcntl), \
    SYSCALL_NAME(flock), \
    SYSCALL_NAME(fsync), \
    SYSCALL_NAME(fdatasync), \
    SYSCALL_NAME(truncate), \
    SYSCALL_NAME(ftruncate), \
    SYSCALL_NAME(getdents), \
    SYSCALL_NAME(getcwd), \
    SYSCALL_NAME(chdir), \
    SYSCALL_NAME(fchdir), \
    SYSCALL_NAME(rename), \
    SYSCALL_NAME(mkdir), \
    SYSCALL_NAME(rmdir), \
    SYSCALL_NAME(creat), \
    SYSCALL_NAME(link), \
    SYSCALL_NAME(unlink), \
    SYSCALL_NAME(symlink), \
    SYSCALL_NAME(readlink), \
    SYSCALL_NAME(chmod), \
    SYSCALL_NAME(fchmod), \
    SYSCALL_NAME(chown), \
    SYSCALL_NAME(fchown), \
    SYSCALL_NAME(lchown), \
    SYSCALL_NAME(umask), \
    SYSCALL_NAME(gettimeofday), \
    SYSCALL_NAME(getrlimit), \
    SYSCALL_NAME(getrusage), \
    SYSCALL_NAME(sysinfo), \
    SYSCALL_NAME(times), \
    SYSCALL_NAME(ptrace), \
    SYSCALL_NAME(getuid), \
    SYSCALL_NAME(syslog), \
    SYSCALL_NAME(getgid), \
    SYSCALL_NAME(setuid), \
    SYSCALL_NAME(setgid), \
    SYSCALL_NAME(geteuid), \
    SYSCALL_NAME(getegid), \
    SYSCALL_NAME(setpgid), \
    SYSCALL_NAME(getppid), \
    SYSCALL_NAME(getpgrp), \
    SYSCALL_NAME(setsid), \
    SYSCALL_NAME(setreuid), \
    SYSCALL_NAME(setregid), \
    SYSCALL_NAME(getgroups), \
    SYSCALL_NAME(setgroups), \
    SYSCALL_NAME(setresuid), \
    SYSCALL_NAME(getresuid), \
    SYSCALL_NAME(setresgid), \
    SYSCALL_NAME(getresgid), \
    SYSCALL_NAME(getpgid), \
    SYSCALL_NAME(setfsuid), \
    SYSCALL_NAME(setfsgid), \
    SYSCALL_NAME(getsid), \
    SYSCALL_NAME(capget), \
    SYSCALL_NAME(capset), \
    SYSCALL_NAME(rt_sigpending), \
    SYSCALL_NAME(rt_sigtimedwait), \
    SYSCALL_NAME(rt_sigqueueinfo), \
    SYSCALL_NAME(rt_sigsuspend), \
    SYSCALL_NAME(sigaltstack), \
    SYSCALL_NAME(utime), \
    SYSCALL_NAME(mknod), \
    SYSCALL_NAME(uselib), \
    SYSCALL_NAME(personality), \
    SYSCALL_NAME(ustat), \
    SYSCALL_NAME(statfs), \
    SYSCALL_NAME(fstatfs), \
    SYSCALL_NAME(sysfs), \
    SYSCALL_NAME(getpriority), \
    SYSCALL_NAME(setpriority), \
    SYSCALL_NAME(sched_setparam), \
    SYSCALL_NAME(sched_getparam), \
    SYSCALL_NAME(sched_setscheduler), \
    SYSCALL_NAME(sched_getscheduler), \
    SYSCALL_NAME(sched_get_priority_max), \
    SYSCALL_NAME(sched_get_priority_min), \
    SYSCALL_NAME(sched_rr_get_interval), \
    SYSCALL_NAME(mlock), \
    SYSCALL_NAME(munlock), \
    SYSCALL_NAME(mlockall), \
    SYSCALL_NAME(munlockall), \
    SYSCALL_NAME(vhangup), \
    SYSCALL_NAME(modify_ldt), \
    SYSCALL_NAME(pivot_root), \
    SYSCALL_NAME(_sysctl), \
    SYSCALL_NAME(prctl), \
    SYSCALL_NAME(arch_prctl), \
    SYSCALL_NAME(adjtimex), \
    SYSCALL_NAME(setrlimit), \
    SYSCALL_NAME(chroot), \
    SYSCALL_NAME(sync), \
    SYSCALL_NAME(acct), \
    SYSCALL_NAME(settimeofday), \
    SYSCALL_NAME(mount), \
    SYSCALL_NAME(umount2), \
    SYSCALL_NAME(swapon), \
    SYSCALL_NAME(swapoff), \
    SYSCALL_NAME(reboot), \
    SYSCALL_NAME(sethostname), \
    SYSCALL_NAME(setdomainname), \
    SYSCALL_NAME(iopl), \
    SYSCALL_NAME(ioperm), \
    SYSCALL_NAME(create_module), \
    SYSCALL_NAME(init_module), \
    SYSCALL_NAME(delete_module), \
    SYSCALL_NAME(get_kernel_syms), \
    SYSCALL_NAME(query_module), \
    SYSCALL_NAME(quotactl), \
    SYSCALL_NAME(nfsservctl), \
    SYSCALL_NAME(getpmsg), \
    SYSCALL_NAME(putpmsg), \
    SYSCALL_NAME(afs_syscall), \
    SYSCALL_NAME(tuxcall), \
    SYSCALL_NAME(security), \
    SYSCALL_NAME(gettid), \
    SYSCALL_NAME(readahead), \
    SYSCALL_NAME(setxattr), \
    SYSCALL_NAME(lsetxattr), \
    SYSCALL_NAME(fsetxattr), \
    SYSCALL_NAME(getxattr), \
    SYSCALL_NAME(lgetxattr), \
    SYSCALL_NAME(fgetxattr), \
    SYSCALL_NAME(listxattr), \
    SYSCALL_NAME(llistxattr), \
    SYSCALL_NAME(flistxattr), \
    SYSCALL_NAME(removexattr), \
    SYSCALL_NAME(lremovexattr), \
    SYSCALL_NAME(fremovexattr), \
    SYSCALL_NAME(tkill), \
    SYSCALL_NAME(time), \
    SYSCALL_NAME(futex), \
    SYSCALL_NAME(sched_setaffinity), \
    SYSCALL_NAME(sched_getaffinity), \
    SYSCALL_NAME(set_thread_area), \
    SYSCALL_NAME(io_setup), \
    SYSCALL_NAME(io_destroy), \
    SYSCALL_NAME(io_getevents), \
    SYSCALL_NAME(io_submit), \
    SYSCALL_NAME(io_cancel), \
    SYSCALL_NAME(get_thread_area), \
    SYSCALL_NAME(lookup_dcookie), \
    SYSCALL_NAME(epoll_create), \
    SYSCALL_NAME(epoll_ctl_old), \
    SYSCALL_NAME(epoll_wait_old), \
    SYSCALL_NAME(remap_file_pages), \
    SYSCALL_NAME(getdents64), \
    SYSCALL_NAME(set_tid_address), \
    SYSCALL_NAME(restart_syscall), \
    SYSCALL_NAME(semtimedop), \
    SYSCALL_NAME(fadvise64), \
    SYSCALL_NAME(timer_create), \
    SYSCALL_NAME(timer_settime), \
    SYSCALL_NAME(timer_gettime), \
    SYSCALL_NAME(timer_getoverrun), \
    SYSCALL_NAME(timer_delete), \
    SYSCALL_NAME(clock_settime), \
    SYSCALL_NAME(clock_gettime), \
    SYSCALL_NAME(clock_getres), \
    SYSCALL_NAME(clock_nanosleep), \
    SYSCALL_NAME(exit_group), \
    SYSCALL_NAME(epoll_wait), \
    SYSCALL_NAME(epoll_ctl), \
    SYSCALL_NAME(tgkill), \
    SYSCALL_NAME(utimes), \
    SYSCALL_NAME(vserver), \
    SYSCALL_NAME(mbind), \
    SYSCALL_NAME(set_mempolicy), \
    SYSCALL_NAME(get_mempolicy), \
    SYSCALL_NAME(mq_open), \
    SYSCALL_NAME(mq_unlink), \
    SYSCALL_NAME(mq_timedsend), \
    SYSCALL_NAME(mq_timedreceive), \
    SYSCALL_NAME(mq_notify), \
    SYSCALL_NAME(mq_getsetattr), \
    SYSCALL_NAME(kexec_load), \
    SYSCALL_NAME(waitid), \
    SYSCALL_NAME(add_key), \
    SYSCALL_NAME(request_key), \
    SYSCALL_NAME(keyctl), \
    SYSCALL_NAME(ioprio_set), \
    SYSCALL_NAME(ioprio_get), \
    SYSCALL_NAME(inotify_init), \
    SYSCALL_NAME(inotify_add_watch), \
    SYSCALL_NAME(inotify_rm_watch), \
    SYSCALL_NAME(migrate_pages), \
    SYSCALL_NAME(openat), \
    SYSCALL_NAME(mkdirat), \
    SYSCALL_NAME(mknodat), \
    SYSCALL_NAME(fchownat), \
    SYSCALL_NAME(futimesat), \
    SYSCALL_NAME(newfstatat), \
    SYSCALL_NAME(unlinkat), \
    SYSCALL_NAME(renameat), \
    SYSCALL_NAME(linkat), \
    SYSCALL_NAME(symlinkat), \
    SYSCALL_NAME(readlinkat), \
    SYSCALL_NAME(fchmodat), \
    SYSCALL_NAME(faccessat), \
    SYSCALL_NAME(pselect6), \
    SYSCALL_NAME(ppoll), \
    SYSCALL_NAME(unshare), \
    SYSCALL_NAME(set_robust_list), \
    SYSCALL_NAME(get_robust_list), \
    SYSCALL_NAME(splice), \
    SYSCALL_NAME(tee), \
    SYSCALL_NAME(sync_file_range), \
    SYSCALL_NAME(vmsplice), \
    SYSCALL_NAME(move_pages), \
    SYSCALL_NAME(utimensat), \
    SYSCALL_NAME(epoll_pwait), \
    SYSCALL_NAME(signalfd), \
    SYSCALL_NAME(timerfd_create), \
    SYSCALL_NAME(eventfd), \
    SYSCALL_NAME(fallocate), \
    SYSCALL_NAME(timerfd_settime), \
    SYSCALL_NAME(timerfd_gettime), \
    SYSCALL_NAME(accept4), \
    SYSCALL_NAME(signalfd4), \
    SYSCALL_NAME(eventfd2), \
    SYSCALL_NAME(epoll_create1), \
    SYSCALL_NAME(dup3), \
    SYSCALL_NAME(pipe2), \
    SYSCALL_NAME(inotify_init1), \
    SYSCALL_NAME(preadv), \
    SYSCALL_NAME(pwritev), \
    SYSCALL_NAME(rt_tgsigqueueinfo), \
    SYSCALL_NAME(perf_event_open), \
    SYSCALL_NAME(recvmmsg), \
    SYSCALL_NAME(fanotify_init), \
    SYSCALL_NAME(fanotify_mark), \
    SYSCALL_NAME(prlimit64), \
    SYSCALL_NAME(name_to_handle_at), \
    SYSCALL_NAME(open_by_handle_at), \
    SYSCALL_NAME(clock_adjtime), \
    SYSCALL_NAME(syncfs), \
    SYSCALL_NAME(sendmmsg), \
    SYSCALL_NAME(setns), \
    SYSCALL_NAME(getcpu), \
    SYSCALL_NAME(process_vm_readv), \
    SYSCALL_NAME(process_vm_writev), \
    SYSCALL_NAME(kcmp), \
    SYSCALL_NAME(finit_module), \
    SYSCALL_NAME(sched_setattr), \
    SYSCALL_NAME(sched_getattr), \
    SYSCALL_NAME(renameat2), \
    SYSCALL_NAME(seccomp), \
    SYSCALL_NAME(getrandom), \
    SYSCALL_NAME(memfd_create), \
    SYSCALL_NAME(kexec_file_load), \
    SYSCALL_NAME(bpf), \
    SYSCALL_NAME(execveat), \
    SYSCALL_NAME(userfaultfd), \
    SYSCALL_NAME(membarrier), \
    SYSCALL_NAME(mlock2), \
    SYSCALL_NAME(copy_file_range), \
    SYSCALL_NAME(preadv2), \
    SYSCALL_NAME(pwritev2), \
    SYSCALL_NAME(pkey_mprotect), \
    SYSCALL_NAME(pkey_alloc), \
    SYSCALL_NAME(pkey_free), \
    SYSCALL_NAME(statx), \
    }

int parse_sandbox(void *opaque, QemuOpts *opts, Error **errp);
int parse_seccomp(void *opaque, QemuOpts *opts, Error **errp);

#endif
